{"name": "Codearte/catch-exception", "id": 25569063, "created_at": "2014-10-22 07:57:34", "watchers_count": 126, "stargazers_count": 126, "forks_count": 16, "updated_at": "2019-09-08 23:10:56", "pushed_at": "2019-04-09 07:14:08", "fetched_at": "2019-10-10 00:57:22", "files": ["catch-exception/pom.xml", "catch-throwable/pom.xml", "pom.xml", ".travis.yml"]}